[action] update bsp build test logic
- using docker as build env, then will not do install logic every time
- update logic to prevent exit directly when build one bsp failed,
  will contine build next bsp.
- split build log by `::group`, ref:
  https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#grouping-log-lines
- generate summary file by `$GITHUB_STEP_SUMMARY`.

Signed-off-by: a1012112796 <1012112796@qq.com>

diff --git a/.github/workflows/action.yml b/.github/workflows/action.yml
--- a/.github/workflows/action.yml
+++ b/.github/workflows/action.yml
@@ -1,4 +1,4 @@
-name: RT-Thread
+name: bsp-build-test
 
 # Controls when the action will run. Triggers the workflow on push or pull request
 # events but only for the master branch
@@ -27,6 +27,10 @@ permissions:
 jobs:
   build:
     runs-on: ubuntu-latest
+    container:
+      # ref: https://github.com/a1012112796/rtt_ci_env
+      image: a1012112796/rtt_ci_env:${{ matrix.legs.RTT_TOOL_CHAIN}}
+
     name: ${{ matrix.legs.RTT_BSP }}
     if: github.repository_owner == 'RT-Thread'
     strategy:
@@ -281,65 +285,13 @@ jobs:
                 - "bouffalo_lab/bl70x"
     steps:
       - uses: actions/checkout@v3
-      - name: Set up Python
-        uses: actions/setup-python@v3
-        with:
-          python-version: 3.8
 
-      - name: Install Tools
+      - name: Config env
         shell: bash
         run: |
-          sudo apt-get update
-          sudo apt-get -qq install gcc-multilib libncurses5-dev scons
-          sudo python -m pip install --upgrade pip -qq
-          pip install requests -qq
           git config --global http.postBuffer 524288000
           python -c "import tools.menuconfig; tools.menuconfig.touch_env()"
           echo "RTT_ROOT=${{ github.workspace }}" >> $GITHUB_ENV
-          echo "RTT_CC=gcc" >> $GITHUB_ENV
-
-      - name: Install Arm ToolChains
-        if: ${{ matrix.legs.RTT_TOOL_CHAIN == 'sourcery-arm' && success() }}
-        shell: bash
-        run: |
-          wget -q https://github.com/RT-Thread/toolchains-ci/releases/download/v1.3/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2
-          sudo tar xjf gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2 -C /opt
-          /opt/gcc-arm-none-eabi-10-2020-q4-major/bin/arm-none-eabi-gcc --version
-          echo "RTT_EXEC_PATH=/opt/gcc-arm-none-eabi-10-2020-q4-major/bin" >> $GITHUB_ENV
-
-      - name: Install AArch64 ToolChains
-        if: ${{ matrix.legs.RTT_TOOL_CHAIN == 'sourcery-aarch64' && success() }}
-        shell: bash
-        run: |
-          wget -q https://github.com/RT-Thread/toolchains-ci/releases/download/v1.6/gcc-arm-10.2-2020.11-x86_64-aarch64-none-elf.tar.xz
-          sudo tar -xf gcc-arm-10.2-2020.11-x86_64-aarch64-none-elf.tar.xz -C /opt
-          /opt/gcc-arm-10.2-2020.11-x86_64-aarch64-none-elf/bin/aarch64-none-elf-gcc --version
-          echo "RTT_EXEC_PATH=/opt/gcc-arm-10.2-2020.11-x86_64-aarch64-none-elf/bin" >> $GITHUB_ENV
-
-      - name: Install Mips ToolChains
-        if: ${{ matrix.legs.RTT_TOOL_CHAIN == 'sourcery-mips' && success() }}
-        shell: bash
-        run: |
-          wget -q https://github.com/RT-Thread/toolchains-ci/releases/download/v1.1/mips-2016.05-7-mips-sde-elf-i686-pc-linux-gnu.tar.bz2
-          sudo tar xjf mips-2016.05-7-mips-sde-elf-i686-pc-linux-gnu.tar.bz2 -C /opt
-          /opt/mips-2016.05/bin/mips-sde-elf-gcc --version
-          echo "RTT_EXEC_PATH=/opt/mips-2016.05/bin" >> $GITHUB_ENV
-
-      - name: Install Riscv64-unknown-elf ToolChains
-        if: ${{ matrix.legs.RTT_TOOL_CHAIN == 'sourcery-riscv64-unknown-elf' && success() }}
-        run: |
-          wget -q https://github.com/RT-Thread/toolchains-ci/releases/download/v1.4/riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14.tar.gz
-          sudo tar zxvf riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14.tar.gz -C /opt
-          /opt/riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14/bin/riscv64-unknown-elf-gcc --version
-          echo "RTT_EXEC_PATH=/opt/riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14/bin" >> $GITHUB_ENV
-
-      - name: Install Riscv-none-embed ToolChains
-        if: ${{ matrix.legs.RTT_TOOL_CHAIN == 'sourcery-riscv-none-embed' && success() }}
-        run: |
-          wget -q https://github.com/RT-Thread/toolchains-ci/releases/download/v1.5/xpack-riscv-none-embed-gcc-8.3.0-2.3-linux-x64.tar.gz
-          sudo tar zxvf xpack-riscv-none-embed-gcc-8.3.0-2.3-linux-x64.tar.gz -C /opt
-          /opt/xpack-riscv-none-embed-gcc-8.3.0-2.3/bin/riscv-none-embed-gcc --version
-          echo "RTT_EXEC_PATH=/opt/xpack-riscv-none-embed-gcc-8.3.0-2.3/bin" >> $GITHUB_ENV
 
       - name: Bsp Scons Compile
         if: ${{ success() }}
@@ -350,10 +302,17 @@ jobs:
           SRTT_BSP: ${{ join(matrix.legs.SUB_RTT_BSP, ',') }}
         run: |
           source ~/.env/env.sh
+          failed=0
           count=0
           for bsp in $(echo $SRTT_BSP | tr ',' '\n'); do
             count=$((count+1))
-            echo "Compiling BSP: ==$count=== $bsp ===="
+            echo "::group::Compiling BSP: ==$count=== $bsp ===="
             pushd bsp/$bsp && pkgs --update && popd
-            scons -C bsp/$bsp -j8
+            scons -C bsp/$bsp -j8 --debug=time | tee output.log || \
+            { total_time=$(grep "Total command execution time" output.log | awk '{print $5}'); \
+              failed=$((failed+1)) ; echo "::endgroup::" ; echo "::error::build $bsp failed" ; \
+              echo "- ❌ build $bsp failed in $total_time seconds " >> $GITHUB_STEP_SUMMARY ; } && \
+            { total_time=$(grep "Total command execution time" output.log | awk '{print $5}'); \
+              echo "- ✅ build $bsp success in $total_time seconds " >> $GITHUB_STEP_SUMMARY ; echo "::endgroup::" ; }
           done
+          exit $failed
